version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/pento
    ports:
      - "4000:4000"
    depends_on:
      - db
